//! The finished tree, kept, so a launch is a read rather than a derivation.
//!
//! **Everything a scan needs was already cached except the answer.** `scancache` holds the
//! expensive ingredients — the tree-sitter parse and `git blame`, keyed by content — and it
//! earns its keep: measured on ceph, a warm scan spends 0.20s parsing and 0.03s blaming
//! against 279s and 6s cold. What it does not hold is the tree those ingredients are folded
//! into, so every launch read 300MB of parse data back, scored 113,322 functions (2.50s, for
//! a number the map never draws — see `isAnalyzed`), rebuilt the tree and aggregated it, to
//! arrive at exactly the same answer as last time.
//!
//! This holds the answer. A launch that finds a valid one skips the parse cache, the scoring
//! and the fold entirely.
//!
//! # What makes it valid
//!
//! Not the commit alone. The scan reads the WORKING TREE, so a cache keyed by HEAD would
//! serve a stale map to anybody with unsaved work — which is everybody, most of the time. The
//! signature is what the scan actually depends on:
//!
//! - every walked file's path, modification time and length — the same pair `scancache` gates
//!   on, and the same one `resync_changed` uses, for the same reason: two writes in one second
//!   can share an mtime;
//! - `HEAD`, because churn, age and blame are read from git and move when a commit lands even
//!   though no file did;
//! - `PARSE_VERSION`, because a parser that has moved means the same bytes yield different
//!   functions — the rule this repo's caches all follow;
//! - the fidelity, because `Ordering` and `Full` compute different scores from identical
//!   input.
//!
//! Computing it costs the walk, which is 0.38s on ceph and is work the scan does anyway.
//!
//! # What it does not cover
//!
//! `.sanity/` readings are not in here — they are loaded separately and folded on top, which
//! is what lets a reading land without invalidating anything. A repo whose readings changed
//! keeps its cached tree and gets its colours from the store, as it always did.

use crate::scan::Scan;
use crate::scan::Fidelity;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// Bumped when the SHAPE of what is stored changes. A stale record here is not dangerous —
/// it is a tree describing a repo that has moved on — but it is unreadable, and a version is
/// how it says so rather than failing to parse.
///
/// 2: binary rather than JSON — see `load`.
/// 3: the parser's version is stored beside the signature, so an unchecked read can still
///    refuse a tree built by a different parser — see `stale`.
/// 4: `Node` gained the clone fields. **A field added to what is STORED here is a version
///    bump even when nothing about the repo changed**, and the reason is the one `file_doc`
///    taught in `scancache`: every one of them is `#[serde(default)]`, so a record written
///    before it loads perfectly and reports `None`. Every repo with a warm tree would have
///    shown an empty Clones lens — correctly according to the file it read, and wrongly about
///    the code — until something unrelated happened to drop the cache.
const VERSION: u32 = 4;

#[derive(Serialize, Deserialize)]
struct Cached {
    version: u32,
    /// What the tree was derived from — see the module note. A mismatch is a rescan.
    signature: u64,
    /// The parser that produced it. Held separately from the signature because `stale` reads
    /// this file WITHOUT computing a signature, and a tree parsed by a different build is
    /// wrong in a way no amount of "the files have not changed" can excuse.
    parse: u32,
    scan: Scan,
}

/// How the tree is written, and the only interesting decision in this file.
///
/// **JSON was the format and it was the whole cost.** Measured on ceph's cache: 67.4MB, read
/// from disk in 0.01s, parsed in **1.15s**. The disk is not the problem and never was — the
/// problem is asking `serde_json` to walk sixty-seven megabytes of punctuation and field
/// names to rebuild 113,322 nodes whose shape was known at compile time.
///
/// A binary encoding does the same job without the text: no key strings, no escaping, no
/// number parsing. The file is smaller and, far more importantly, it is read at memcpy speed
/// rather than at parser speed.
///
/// The cost of choosing it is that the file stops being readable with `jq`, which for a cache
/// nobody debugs by hand — it is regenerated by deleting it — is not much of a cost. The
/// caches a person DOES read (`.sanity/`, the endpoint file) stay text.
fn config() -> bincode::config::Configuration {
    bincode::config::standard()
}

/// The signature for `repo` as it stands, walking it to find out. For callers outside the
/// scan — see `slim`.
pub fn current(repo: &Path, fidelity: Fidelity) -> u64 {
    signature(repo, &crate::scan::collect_files(repo), fidelity)
}

/// The map WITHOUT its functions, if the stored one still describes this repo.
///
/// **What the window draws is eight thousand shapes; what the tree holds is a hundred and
/// thirteen thousand.** Decoding the rest to hand over the part that gets drawn was 0.38s of
/// every project switch, for functions the backend wants and the picture does not: the ring
/// inside a file arrives from `file_functions` when there is somewhere to put it, and the
/// reading queue wants them when somebody presses Read.
///
/// So the trimmed tree is written beside the whole one and read on its own. A launch draws
/// from this; the full tree lands behind it.
pub fn slim(repo: &Path, signature: u64) -> Option<Scan> {
    let cached = read_slim(repo)?;
    (cached.signature == signature).then_some(cached.scan)
}

/// The last map this repo had, without asking whether it is still true.
///
/// **The picture goes up first and the question is asked behind it.** Proving a cached tree
/// current means walking the repo and stat-ing every file — 0.25s on ceph, and the only thing
/// left between a launch and an instant one. It is also work whose answer is almost always
/// "nothing has changed": a repo changes at the speed of somebody typing in it, and the scan
/// that follows this by a fraction of a second replaces the map if it did.
///
/// So the map is drawn from the last one, and the scan behind it either confirms it or
/// supersedes it. What is NOT skipped is the parser: a tree built by a different build of
/// this app describes functions that no longer exist by those names, and no staleness
/// argument covers that.
pub fn stale(repo: &Path) -> Option<Scan> {
    let cached = read_slim(repo)?;
    (cached.parse == crate::parse::PARSE_VERSION).then_some(cached.scan)
}

fn read_slim(repo: &Path) -> Option<Cached> {
    let bytes = std::fs::read(slim_path(repo)?).ok()?;
    let (cached, _): (Cached, usize) = bincode::serde::decode_from_slice(&bytes, config()).ok()?;
    (cached.version == VERSION).then_some(cached)
}

fn slim_path(repo: &Path) -> Option<PathBuf> {
    path_for(repo).map(|p| p.with_extension("slim.bin"))
}

fn path_for(repo: &Path) -> Option<PathBuf> {
    let dir = crate::reports::data_dir()?.join("trees");
    std::fs::create_dir_all(&dir).ok()?;
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in repo.to_string_lossy().as_bytes() {
        h ^= *b as u64;
        h = h.wrapping_mul(0x1000_0000_01b3);
    }
    Some(dir.join(format!("{h:016x}.bin")))
}

/// Fold one more value into a running FNV.
fn mix(h: &mut u64, bytes: &[u8]) {
    for b in bytes {
        *h ^= *b as u64;
        *h = h.wrapping_mul(0x1000_0000_01b3);
    }
}

/// What this scan depends on, as one number. See the module note for what is in it and why.
pub fn signature(repo: &Path, files: &[(PathBuf, crate::model::Lang)], fidelity: Fidelity) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    mix(&mut h, &crate::parse::PARSE_VERSION.to_le_bytes());
    mix(&mut h, &VERSION.to_le_bytes());
    mix(&mut h, if fidelity == Fidelity::Full { b"full" } else { b"ordering" });
    mix(&mut h, head_of(repo).as_bytes());
    // **`.sanityignore`, because it decides what is in scope and is not a source file.**
    // Caught by `an_excluded_file_leaves_the_queue_and_stays_in_the_count` on the first run
    // of this cache: the walk only lists parseable files, so a repo that gained an ignore
    // rule had an identical signature and was served a tree that knew nothing about it. Its
    // bytes rather than its mtime — a rule edited back to what it was is the same scope.
    if let Ok(rules) = std::fs::read(repo.join(".sanityignore")) {
        mix(&mut h, &rules);
    }
    for (path, _) in files {
        mix(&mut h, path.to_string_lossy().as_bytes());
        // Absent metadata mixes nothing, which makes a file that cannot be stat-ed look
        // unchanged. It is the same file the walk found a moment ago; if it has since gone,
        // the parse will say so and the scan that follows is the correct one anyway.
        if let Ok(m) = std::fs::metadata(path) {
            mix(&mut h, &m.len().to_le_bytes());
            if let Ok(t) = m.modified() {
                if let Ok(d) = t.duration_since(std::time::UNIX_EPOCH) {
                    mix(&mut h, &d.as_nanos().to_le_bytes());
                }
            }
        }
    }
    h
}

fn head_of(repo: &Path) -> String {
    std::process::Command::new("git")
        .arg("-C")
        .arg(repo)
        .args(["rev-parse", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_default()
}

/// The stored tree, if it describes this repo as it stands.
pub fn load(repo: &Path, signature: u64) -> Option<Scan> {
    let bytes = std::fs::read(path_for(repo)?).ok()?;
    let (cached, _): (Cached, usize) =
        bincode::serde::decode_from_slice(&bytes, config()).ok()?;
    (cached.version == VERSION && cached.signature == signature).then_some(cached.scan)
}

/// Keep this tree for next time. A failed write costs a derivation, never an answer, so
/// nothing is reported — the same rule the timeline cache follows.
pub fn save(repo: &Path, signature: u64, scan: &Scan) {
    let Some(path) = path_for(repo) else { return };
    let Ok(bytes) = bincode::serde::encode_to_vec(
        Cached {
            version: VERSION,
            signature,
            parse: crate::parse::PARSE_VERSION,
            scan: scan.clone(),
        },
        config(),
    ) else {
        return;
    };
    let tmp = path.with_extension("tmp");
    if std::fs::write(&tmp, bytes).is_ok() {
        // Renamed rather than written in place: a launch that reads a half-written tree would
        // draw a repo with a hole in it, and the hole would look like data.
        let _ = std::fs::rename(&tmp, &path);
    }
    // The drawable half, beside it — see `slim`. Written second and read first, which is the
    // safe order: a slim file with no whole one behind it costs a scan, while the reverse
    // would be a map with no functions under it and no way to notice.
    let Some(thin) = slim_path(repo) else { return };
    let Ok(bytes) = bincode::serde::encode_to_vec(
        Cached {
            version: VERSION,
            signature,
            parse: crate::parse::PARSE_VERSION,
            scan: Scan { root: scan.root.slim(), stats: scan.stats.clone() },
        },
        config(),
    ) else {
        return;
    };
    let tmp = thin.with_extension("tmp");
    if std::fs::write(&tmp, bytes).is_ok() {
        let _ = std::fs::rename(&tmp, &thin);
    }
}

#[cfg(test)]
mod tests {
    /// What the drawable half costs to read, against the whole tree. Ignored: a measurement,
    /// `REPO=/path/to/repo cargo test -- --ignored --nocapture halves`.
    #[test]
    #[ignore]
    fn halves() {
        let repo = std::env::var("REPO").expect("REPO=/path/to/repo");
        let repo = std::path::Path::new(&repo);
        let t = std::time::Instant::now();
        let sig = super::current(repo, crate::scan::Fidelity::Ordering);
        let walk = t.elapsed();
        // What a launch actually does: read the last map without proving it — see `stale`.
        let t = std::time::Instant::now();
        let thin = super::stale(repo).expect("a slim tree is cached");
        let slim = t.elapsed();
        let t = std::time::Instant::now();
        let whole = super::load(repo, sig).expect("a whole tree is cached");
        let full = t.elapsed();
        let count = |s: &crate::scan::Scan| {
            let mut n = 0;
            s.root.visit(&mut |_| n += 1);
            n
        };
        println!(
            "walk {:.2}s · slim {:.2}s ({} nodes) · whole {:.2}s ({} nodes)",
            walk.as_secs_f64(),
            slim.as_secs_f64(),
            count(&thin),
            full.as_secs_f64(),
            count(&whole),
        );
    }

    /// Where the time goes when a launch reads its cached tree. Ignored: a measurement,
    /// `TREE=/path/to/cache.bin cargo test -- --ignored --nocapture split`.
    #[test]
    #[ignore]
    fn split() {
        let path = std::env::var("TREE").expect("TREE=/path/to/cache.bin");
        let t = std::time::Instant::now();
        let bytes = std::fs::read(&path).expect("reads");
        let read = t.elapsed();
        let t = std::time::Instant::now();
        let (cached, _): (super::Cached, usize) =
            bincode::serde::decode_from_slice(&bytes, super::config()).expect("decodes");
        let parse = t.elapsed();
        let mut funcs = 0;
        cached.scan.root.visit(&mut |n| {
            if n.kind == crate::model::NodeKind::Func {
                funcs += 1;
            }
        });
        println!(
            "{:.1} MB · read {:.2}s · decode {:.2}s · {funcs} functions",
            bytes.len() as f64 / 1e6,
            read.as_secs_f64(),
            parse.as_secs_f64(),
        );
    }
}
